image: biber.init7.net:4567/tv7/android/builder:master

before_script:
  - chmod +x ./gradlew

stages:
  - build


build:
  stage: build
  script:
    - mkdir aar
    - ./gradlew :library:assembleRelease
    - ./gradlew :library-core:assembleRelease
    - ./gradlew :library-dash:assembleRelease
    - ./gradlew :library-hls:assembleRelease
    - ./gradlew :library-smoothstreaming:assembleRelease
    - ./gradlew :library-ui:assembleRelease
    - ./gradlew :extension-cast:assembleRelease
    - ./gradlew :extension-cronet:assembleRelease
    - ./gradlew :extension-ffmpeg:assembleRelease
    - ./gradlew :extension-flac:assembleRelease
    - ./gradlew :extension-gvr:assembleRelease
    - ./gradlew :extension-ima:assembleRelease
    - ./gradlew :extension-jobdispatcher:assembleRelease
    - ./gradlew :extension-leanback:assembleRelease
    - ./gradlew :extension-mediasession:assembleRelease
    - ./gradlew :extension-okhttp:assembleRelease
    - ./gradlew :extension-opus:assembleRelease
    - ./gradlew :extension-rtmp:assembleRelease
    - ./gradlew :extension-vp9:assembleRelease
    - cp library/*/buildout/outputs/aar/*-release.aar ./aar/
    - cp extensions/*/buildout/outputs/aar/*-release.aar ./aar/
  artifacts:
    paths:
      - 'aar/'
  tags:
    - build


variables:
  GIT_SUBMODULE_STRATEGY: normal